### ISSUE TITLE
Backup folder is created as root

### ISSUE THREAD

**Issue by watchingdogs** [itzg/docker-mc-backup#110]
Not sure if this is intentional or not, but the backup folder and the contents in it are owned by the root user. Running docker as root is required in my environment. I was wondering if there is a way to change this without having to run separate scripts to change the ownership. This issue doesn't appear with the docker-minecraft-server image.

**Comment by itzg** [comment]
You could try setting the user for the container with `--user` on docker run or equivalent in compose.
