### ISSUE TITLE
Add curl to the containter

### ISSUE THREAD

**Issue by jonbranan** [itzg/docker-mc-backup#140]
When trying to use `POST_BACKUP_SCRIPT` with `curl -m 10 https://healthchecks.domain.tld/ping/<uuid>` the container exits of course because curl isn't available in the container.

Is it possible, please, to add curl to the container? Alternatively, could we add support for a ping url?

**Comment by jonbranan** [comment]
Actually, this might not be neccessary. I looked up and down through the documentation and old issues and couldn't find anything to meet my needs. I then looked up alpine and the included binaries and saw wget comes with alpine. Sooooo you can simply use wget instead:

`wget --no-cache --spider https://healthchecks.domain.tld/ping/<uuid>`

Is this something you would like to add to your documentation? I am happy to open a PR.

**Comment by itzg** [comment]
That's odd, I usually include curl instead of wget, if either of those. I can add curl at some point or you/someone can submit a PR.

**Comment by itzg** [comment]
Resolved by #141
