### ISSUE TITLE
Is it possible that excluding files of type .jar could potentially lead to unexpected issues?

### ISSUE THREAD

**Issue by Kagenui-yozuru** [itzg/docker-mc-backup#162]
I've observed that the default value of the `EXCLUDES` environment variable is `*.jar,cache,logs,*.tmp`, which excludes all `.jar` files.
Could this lead to unexpected situations? In my server, I have installed mods (which are all .jar files), and using the default `EXCLUDES` configuration would result in the mods within the `mods/` folder not being backed up, causing issues when restoring the server and preventing it from starting properly. 
Additionally, there are other jar files outside the `mods/` folder whose purposes I am unaware of, although they do consume a significant amount of space. Considering a better approach to exclude jar files other than those in the `mods/` folder, would it be worth considering an upgrade to the exclusion strategy? For example, supporting the following format:
 `EXCLUDES=*.jar,!mods/*.jar`.

**Comment by itzg** [comment]
That is only the default. You can override it with the patterns you want or setting to an empty string to exclude nothing.

If using `tar` as the backup method, then anything supported by [its `--exclude` option](https://manpages.ubuntu.com/manpages/jammy/en/man1/tar.1.html#options) can be provided which will be any [glob pattern](https://manpages.ubuntu.com/manpages/jammy/en/man7/glob.7.html).

**Comment by Kagenui-yozuru** [comment]
ok，Thank you for your response.
