### ISSUE TITLE
Error querying the server after upgrade to 1.20.4

### ISSUE THREAD

**Issue by dj3520-git** [itzg/docker-mc-backup#166]
After upgrading to 1.20.4 I had the below issue (now fixed).
https://github.com/itzg/docker-minecraft-server/issues/2545

mc-backup also seems to be affected. It can connect via RCON and perform the backup fine, but once it's finished it seems unable to query the server:
`ERROR Error querying the server, waiting 5m...`

Having a quick check of the debug output the issue looks to be the same:
`2024-02-04T10:53:10.036Z	DEBUG	mc-monitor/java_status.go:85	ping returned	{"error": "json: cannot unmarshal string into Go struct field ServerInfo.description of type mcpinger.RegularChatComponent", "info": {"version":{"name":"1.20.4","protocol":765},"players":{"max":0,"online":0,"Sample":null},"description":{"text":"","bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"","extra":null},"favicon":""}}`

**Comment by itzg** [comment]
Thanks for reporting this. I need to upgrade the mc-monitor tool.

**Comment by dj3520-git** [comment]
Amazing, thanks for sorting that so quickly!
