### ISSUE TITLE
rsync doesn't prune

### ISSUE THREAD

**Issue by toddejohnson** [itzg/docker-mc-backup#168]
In testing I finally hit prune and the find command doesn't `rm -rf` it `-delete` which is like `rmdir` so I need to get a PR fixing this. Filing an issue so I don't forget. Feel free to assign to me. 

https://github.com/itzg/docker-mc-backup/blob/3b076c4c9a442ae58fdeff140c5e4d9670715dc9/scripts/opt/backup-loop.sh#L317C1-L318C1

**Comment by itzg** [comment]
Thanks for following up that.
