### ISSUE TITLE
[Bug] `rsync` is deleting the backup right after creating it

### ISSUE THREAD

**Issue by johnsturgeon** [itzg/docker-mc-backup#174]
I wanted to have the backup to use rsync instead of tar'ing the file, so I recently swapped, and no matter what I do, the backup gets removed the instant it's done.

You can see the log file below.  No clue why it would prune a backup that's clearly timestamped today.

```
2024-04-15T14:24:25-0700 INFO Pruning backup files older than 2 days
2024-04-15T14:24:25-0700 INFO Removing /backups/world-20240415-142230
```

**Comment by itzg** [comment]
Thanks for reporting this. 

It looks like there might be a bug here

https://github.com/itzg/docker-mc-backup/blob/648cee5e3cc04983893f606293298302ea23e7e7/scripts/opt/backup-loop.sh#L280

where `-mtime` expects units of hours, not days.

**Comment by itzg** [comment]
Actually, `find` on Alpine accepts units of days for `-mtime`

```
	-mtime DAYS	mtime is greater than (+N), less than (-N),
			or exactly N days in the past
```

In that case I'm not sure why it is pruning a directory that is created on the same day.

**Comment by johnsturgeon** [comment]
I'll play around a bit from inside the image, does seem odd though.

Are you able to reproduce it?

**Comment by johnsturgeon** [comment]
I think I found the problem
```
7732c1635b36:/backups# ls -l
total 4
lrwxrwxrwx  1 1000 1000   21 Apr 15 15:18 latest -> world-20240415-151650
drwxrwxr-x 10 1000 1000 4096 Jan  9 19:47 world-20240415-151650
7732c1635b36:/backups# date
Tue Apr 16 07:00:49 PDT 2024
```
I think rsync is setting the timestamp of the folder to that of the original source

**Comment by johnsturgeon** [comment]
I have created a local branch to fix the issue, and I tested it on my machine (works).

What's the process for submitting branches?
[0001-Fixes-rsync-prune-issue-174.patch](https://github.com/itzg/docker-mc-backup/files/14998421/0001-Fixes-rsync-prune-issue-174.patch)

**Comment by itzg** [comment]
Glad to hear you found the issue and a fix. The github docs will give a nice overview of PR process. Basically you'll fork the repo, push your branch, and then submit a PR.

**Comment by johnsturgeon** [comment]
> Glad to hear you found the issue and a fix. The github docs will give a nice overview of PR process. Basically you'll fork the repo, push your branch, and then submit a PR.

Will do!

**Comment by toddejohnson** [comment]
Just for reference `-a` is the same as ` -rlptgoD`

```
       --recursive, -r          recurse into directories
       --links, -l              copy symlinks as symlinks
       --perms, -p              preserve permissions
       --times, -t              preserve modification times
       --group, -g              preserve group
       --owner, -o              preserve owner (super-user only)
       -D                       same as --devices --specials
```

Another option would be `-rlpgoD` which wouldn't preserve times. This might however null the benefit of `--link-dest` as the times of files would change causing them to not be "links." I think the `touch` is an awesome way to make this work!!!!
