### ISSUE TITLE
PRUNE_RESTIC_RETENTION may not be stringified

### ISSUE THREAD

**Issue by Paradoxon1994** [itzg/docker-mc-backup#19]
The env variable may not be stringified since restic then does not recognize it anymore (when calling it via the cli).
See changes to main branch.

**Comment by itzg** [comment]
I double checked the code and I don't see the problem yet. Can you clarify what you have observed? Any logs showing an error and/or the specific change you mean?

**Comment by Paradoxon1994** [comment]
Sorry, I will clarify. 
So apparently when the prune (restic case) is called, you put "" around the retention after evaluating it. 
Unfortunately restic does not take the flag if you are stringifying it.

**Comment by itzg** [comment]
How are you configuring the container? I added this example compose file, which works for me:

https://github.com/itzg/docker-mc-backup/blob/master/examples/docker-compose.restic.yml

**Comment by Paradoxon1994** [comment]
Did you use the multiarch image?

**Comment by itzg** [comment]
> Did you use the multiarch image?

Now I get the same error. The `multiarch` clarification helped a lot.

**Comment by itzg** [comment]
The latest `itzg/mc-backup:multiarch` should now fix this.

**Comment by Paradoxon1994** [comment]
Thank you very much, I will check this later!

**Comment by Paradoxon1994** [comment]
Works just fine, thanks a lot!

**Comment by Paradoxon1994** [comment]
Works just fine, thanks!
