### ISSUE TITLE
rm: missing operand

### ISSUE THREAD

**Issue by Blade920199** [itzg/docker-mc-backup#195]
Running it on Docker Desktop with the following variables.
PAUSE_IF_NO_PLAYERS=true
PRUNE_BACKUPS_COUNT=20
BACKUP_INTERVAL=2h
RCON_PASSWORD=###REDACTED###
RCON_HOST=172.17.0.2
RCON_PORT=25575

Docker Run: docker run --hostname=91782db01d7e --env=PAUSE_IF_NO_PLAYERS=true --env=PRUNE_BACKUPS_COUNT=20 --env=BACKUP_INTERVAL=2h --env=RCON_PASSWORD=###REDACTED### --env=RCON_HOST=172.17.0.2 --env=RCON_PORT=25575 --env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin --env=HOME=/tmp --volume=/backups --volume=/data --network=bridge --workdir=/backups --restart=no --label='org.opencontainers.image.created=2024-07-08T01:00:41.165Z' --label='org.opencontainers.image.description=Provides a side-car container to backup itzg/minecraft-server world data' --label='org.opencontainers.image.licenses=MIT' --label='org.opencontainers.image.revision=a6f960c1f5eea0e8ffa5062064844b0f721571b9' --label='org.opencontainers.image.source=https://github.com/itzg/docker-mc-backup' --label='org.opencontainers.image.title=docker-mc-backup' --label='org.opencontainers.image.url=https://github.com/itzg/docker-mc-backup' --label='org.opencontainers.image.version=master' --runtime=runc -d itzg/mc-backup:latest
![image](https://github.com/itzg/docker-mc-backup/assets/97499172/0f4c5bcc-f27d-493d-b6a8-7858f428fa5c)

**Comment by itzg** [comment]
Thanks for reporting this.
