### ISSUE TITLE
Improve logging when `PAUSE_IF_NO_PLAYERS` is enabled

### ISSUE THREAD

**Issue by 0237h** [itzg/docker-mc-backup#202]
Hi,

Currently there is no useful log related to the `PAUSE_IF_NO_PLAYERS` feature coming from the image. The loop just run without any indication (unless there's an error).

https://github.com/itzg/docker-mc-backup/blob/3d04028e75df576fc1bdf83a177c83fe30c58a9d/scripts/opt/backup-loop.sh#L616-L629

I noticed this when thinking that the backups weren't working because the container didn't show any logs, until I realized there were no players during that time therefore no backups were created.

I think it would be nice to have some kind of message like when the script sleeps for the next backup. Something like:

```diff
if [[ ${PAUSE_IF_NO_PLAYERS^^} = TRUE ]]; then
  while true; do
    if is_paused; then
+     log INFO "Server is paused, sleeping for ${PLAYERS_ONLINE_CHECK_INTERVAL} before retrying..."
      sleep "${PLAYERS_ONLINE_CHECK_INTERVAL}"
    elif ! PLAYERS_ONLINE=$(mc-monitor status --host "${SERVER_HOST}" --port "${SERVER_PORT}" --show-player-count 2>&1); then
      log ERROR "Error querying the server, waiting ${PLAYERS_ONLINE_CHECK_INTERVAL}..."
      sleep "${PLAYERS_ONLINE_CHECK_INTERVAL}"
    elif [ "${PLAYERS_ONLINE}" = 0 ]; then
+     log INFO "No players online, sleeping for ${PLAYERS_ONLINE_CHECK_INTERVAL} before retrying..."
      sleep "${PLAYERS_ONLINE_CHECK_INTERVAL}"
    else
      break
    fi
  done
fi
```
Could be configurable (with `$DEBUG` ?).

**Comment by itzg** [comment]
Good point. Enabling DEBUG would already show the commands happening, so the proposed log makes sense to always be present. 

A PR would be great.
