### ISSUE TITLE
Instantly create backups by command at any time

### ISSUE THREAD

**Issue by AkkyOrz** [itzg/docker-mc-backup#35]
Hello. First of all, thank you for an amazing product!

I want to create backups at the time I want to create a backup in addition to the periodical backups.
From what I have read in the backup script(`backup-loop.sh`), the following part appeared to be performing the backup function.

https://github.com/itzg/docker-mc-backup/blob/d8cad71ef74aec8ca6f7c811a41f59f13ccb4123/backup-loop.sh#L159-L199

Is it possible to separate the backup function for this part?
For example, I would like to run it from the command line like this.
`docker exec -it mc-backup <backup script>.sh`
I would appreciate it if you could consider it.
Please let me know if the feature already exists.
Thanks.

**Comment by itzg** [comment]
That would be a useful feature and no, the script doesn't yet allow for that. With a few small changes I think I could introduce a one-shot mode.

**Comment by itzg** [comment]
The latest image now supports one-off/on-demand backups:

https://github.com/itzg/docker-mc-backup#on-demand-backups

**Comment by AkkyOrz** [comment]
Wow!! Thanks for your quick implementation!
I have checked the image, and It seems working as I expected.
I love this function.
Thank you!!:blush:

**Comment by itzg** [comment]
Awesome! It was a great idea you suggested.
