### ISSUE TITLE
Restic prune log message is misleading

### ISSUE THREAD

**Issue by djmattyg007** [itzg/docker-mc-backup#38]
The log message says the following:

```
log INFO "Forgetting snapshots older than ${PRUNE_BACKUPS_DAYS} days"
```

But that environment variable isn't actually used when running `restic forget` if you've overridden `PRUNE_RESTIC_RETENTION`.

**Comment by itzg** [comment]
At first I was thinking the same thing, but when I went to double check the unit of time I noticed and remembered that `PRUNE_RESTIC_RETENTION` is the command-line argument that references `PRUNE_BACKUP_DAYS`:

https://github.com/itzg/docker-mc-backup/blob/fc26de80a37214003ab337b952a66b849715c18c/backup-loop.sh#L18

So the log seems to be correct.

**Comment by djmattyg007** [comment]
But that's only relevant if you're using the default value. If you've manually set `PRUNE_RESTIC_RETENTION`, `PRUNE_BACKUP_DAYS` isn't relevant at all.

Unfortunately it's also still required to be set even if it's not technically in use, otherwise pruning won't happen at all.

**Comment by itzg** [comment]
Good point. If I remove the "days" qualifier then the log will read better the proper variable there.

**Comment by itzg** [comment]
The latest image now includes the corrected log message.
