### ISSUE TITLE
UTC TimeZone in filename

### ISSUE THREAD

**Issue by Beriks4** [itzg/docker-mc-backup#42]
Hello, in filename you used `ts=$(date -u +"%Y%m%d-%H%M%S")`
thus, even if a time zone (TZ) is defined, the file name will contain the time in the UTC:
`2021-11-07T19:18:56+0300 INFO Backing up content in /data to /backups/world-20211107-161856.tgz`
Maybe you can delete -u flag?

**Comment by itzg** [comment]
The latest image should now fix this.
