### ISSUE TITLE
restic mode should make use of `--hostname` to avoid dependence on container name

### ISSUE THREAD

**Issue by itzg** [itzg/docker-mc-backup#55]
In regular Docker the container name and therefore hostname can be stabilized easily. In kubernetes the container’s hostname is the pod name. With statefulsets that pod name will be stable, but not with deployments. 

It seems like `BACKUP_NAME` could be used, but more thought is needed.

**Comment by kevinkjt2000** [comment]
I'd happily opt-in to testing this option. I came across https://github.com/restic/restic/issues/1984#issuecomment-418862391 today. Then I was delighted and sad about all the parameters being properly handled to avoid expansion on the `restic backup` command here: https://github.com/itzg/docker-mc-backup/blob/b95ac21412f821514e19ca7a23f5282932bb6ccc/backup-loop.sh#L300

What about an environment variable (`RESTIC_HOSTNAME` perhaps?) that defaults to the value of `BACKUP_NAME` when not set?

**Comment by itzg** [comment]
Thanks @kevinkjt2000 for pointing out that option. Giving the fallback value some more thought, I decided to have it fallback to the hostname/container name since that keeps the behavior the same for those that depended on that.
