### ISSUE TITLE
backup method "rsync"

### ISSUE THREAD

**Issue by atfrase** [itzg/docker-mc-backup#90]
It would be great to have a BACKUP_METHOD that simply makes a straight copy of the loose world files using i.e. `rsync`, without archiving or compressing them like `tar`. Further rolling or incremental backups could be made from that snapshot using any desired backup tool, or other tools could be run on it such as generating world maps, safe in the knowledge that the snapshot is internally consistent.

**Comment by itzg** [comment]
That's a good idea.

**Comment by toddejohnson** [comment]
Something similar to this was implemented in #165. Could likely be closed?

**Comment by itzg** [comment]
Yep, let's close this as done!
