### ISSUE TITLE
Backup exits with command not found when file is changed while reading

### ISSUE THREAD

**Issue by wilcockj** [itzg/docker-mc-backup#94]
![image](https://user-images.githubusercontent.com/33857120/175786613-7f392688-9dab-47d9-ab9c-cee444357242.png)

The container exits with code 127 even though it says successful. Happens when backuping using tar method and has error in compression due to file changing while reading. And then goes to a line with next command which isn't found.
https://github.com/itzg/docker-mc-backup/blob/b0ee95d42af707a17d45bf45a6ec22971dd622c3/backup-loop.sh#L220

I'm not sure what "next" is supposed to do in this case? Should it instead be continue

The backup container is running with docker compose. Haven't changed anything within the container which had been working, but have added spigot plugins which seem to be causing the error. Any idea how to get around this?
Thank you

**Comment by itzg** [comment]
Yes, it's supposed to be a `continue` 😬
